config/routes.rb
Rails.application.routes.draw do
    get 'donetasks/index'

    devise_for :users, controllers: {
       registrations: 'users/registrations'
    }

    resources :tasks

    post '/tasks/:task_id/donetasks', to: 'donetasks#create', as: 'create_donetask'
    delete '/tasks/:task_id/donetasks', to: 'donetasks#destroy', as: 'destroy_donetask'

      # resources :donetasks, only: [:create, :destroy], as: ['create_task']


    # resources :users do
    #   resources :donetasks, only: :create
    # end

    root to:'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :donetasks
  has_many :users, through: :donetasks, dependent: :destroy

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :completed_tasks
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @users = @task.users
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :photo, :description)
    end

    def completed_tasks
      @tareas_totales = Task.all.count
      @user = current_user
      @tareas_realizadas = current_user.donetasks.count
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tareas Dieciocheras</h1>

<%= link_to 'New Task', new_task_path, class: "btn btn-success text-white"  %>

<div class="row">
  <% @tasks.each do |task| %>
    <div class="col">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= task.photo %>" alt="<%= task.name %>">
          <div class="card-body">
            <h5 class="card-title"> <%= task.name %></h5>
            <p class="card-text"><%= task.description %></p>
            <td><%= link_to 'Ver Detalles', task, class: "btn btn-primary text-white" %></td>
            <td><%= link_to 'Editar', edit_task_path(task), class: "btn btn-warning text-white" %></td>
            <td><%= link_to 'Borrar', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger text-white"  %></td>

            <% if current_user.tasks.include?(task) %>
              <td><%= link_to 'Desmarcar', destroy_donetask_path(task), method: :delete, class: "btn btn-light" %></td>
            <% else  %>
              <td><%= link_to 'Marcar', create_donetask_path(task), method: :post, class: "btn btn-dark text-white" %></td>
            <% end  %>

          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%=  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%= @task.photo %>" alt="<%= @task.name %>">
  <div class="card-body">
    <h5 class="card-title"> <%= @task.name %></h5>
    <p class="card-text"><%= @task.description %></p>
    <td><%= link_to 'Editar', edit_task_path(@task), class: "btn btn-warning text-white" %></td>
    <td><%= link_to 'Back', tasks_path, class: "btn btn-danger text-white"  %></td>
  </div>
</div>



<% ranking = 0 %>

<div class="row">
  <% @users.limit(5).each do |user| %>
    <div class="col">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= user.photo %>" alt="<%= user.name %>">
          <div class="card-body">
            <h5 class="card-title"> <%= user.name %></h5>
            <p class="card-text">Ranking: <%= ranking += 1 %></p>
          </div>
        </div>
    </div>
  <% end %>
</div>

<% new_ranking = 0 %>

<div class="row">
  <div class="col-md-4">

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Ranking</th>
          <th scope="col">Nombre</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= new_ranking += 1 %></td>
            <td><%= user.name %></td>
          </tr>
        <% end %>

      </tbody>
    </table>

  </div>
</div>